### PR TITLE
Updated to core24 and gnome-46-2404

### PR DESCRIPTION
**Pull request by jssotomdz**

### CODE REVIEW

**Review by sergio-costas — APPROVED** [review]
Changes look sensible.

**Comment by sergio-costas** [comment]
I see that it requires an old version of gnome-games...

**Comment by jssotomdz** [comment]
> I see that it requires an old version of gnome-games

not sure why some games started asking for that dependency

**Comment by sergio-costas** [comment]
Maybe because no one wanted to update the code to libgnome-games 2.0 :-D

**Comment by jssotomdz** [comment]
> no one wanted to update the code

yes, some of these games are a bit outdated

**Pull request merged**
